# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerContentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('concentration', models.FloatField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_logs', to='tubes.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContainerKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('concentration', models.FloatField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tubes.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(null=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('order', models.IntegerField()),
                ('containerA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tubes.Container')),
                ('containerB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tubes.Container')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tubes.Substance')),
                ('transfer_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_logs', to='tubes.TransferGroup')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TransferPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('containerA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tubes.Container')),
                ('containerB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tubes.Container')),
                ('transfer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_plans', to='tubes.TransferGroup')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5)),
                ('long_name', models.CharField(max_length=30)),
                ('to_ml', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='transferlog',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tubes.Unit'),
        ),
        migrations.AddField(
            model_name='content',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tubes.Substance'),
        ),
        migrations.AddField(
            model_name='content',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tubes.Unit'),
        ),
        migrations.AddField(
            model_name='containerkind',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tubes.Unit'),
        ),
        migrations.AddField(
            model_name='containercontentlog',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tubes.Substance'),
        ),
        migrations.AddField(
            model_name='containercontentlog',
            name='transfer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_contents', to='tubes.TransferGroup'),
        ),
        migrations.AddField(
            model_name='containercontentlog',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tubes.Unit'),
        ),
        migrations.AddField(
            model_name='container',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tubes.ContainerKind'),
        ),
        migrations.AlterUniqueTogether(
            name='transferplan',
            unique_together=set([('containerA', 'containerB', 'transfer_group'), ('transfer_group', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='transferlog',
            unique_together=set([('containerA', 'containerB', 'transfer_group'), ('transfer_group', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set([('substance', 'container')]),
        ),
        migrations.AlterUniqueTogether(
            name='containercontentlog',
            unique_together=set([('substance', 'container')]),
        ),
    ]
