# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tubes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfergroup',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
