# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubes', '0003_auto_20170203_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='long_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
